# This is a basic workflow to help you get started with Actions

name: first workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firstjob:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: firstjob script
        shell: cmd
        run: echo Hello, world! This is the first job
        
  secondjob:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: secondjob script
        run: |
          echo this is the second job
          echo and this is a multiline script
